name: Playwright Tests
on:
  # execute on deployment to preview environment
  # https://cushionapp.com/journal/how-to-use-playwright-with-github-actions-for-e2e-testing-of-vercel-preview
  deployment_status:
jobs:
  playwright-tests:
    if: github.event.deployment_status.state == 'success'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    # Cache Playwright browsers to speed up subsequent runs  
    # https://dev.to/ayomiku222/how-to-cache-playwright-browser-on-github-actions-51o6
    - name: Get installed Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
    - name: Cache playwright binaries
      uses: actions/cache/restore@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install dependencies
      run: npm ci
    - run: npx playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    - run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    - name: Run Playwright tests
      env:
        BASE_URL: ${{ github.event.deployment_status.environment_url }}
        VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
    # - name: 'notify vercel'
    #   uses: 'vercel/repository-dispatch/actions/status@v1'
    #   with:
    #     # name of _this_ workflow (line: 11: jobs.playwright-tests)
    #     name: 'Vercel - hnsl.io: playwright-tests'
    
    - name: Save Playwright binaries to cache
      id: playwright-cache-save
      if: always() && steps.playwright-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
        path: |
          ~/.cache/ms-playwright
